import React from 'react';

const About = () => {
    return (
        <main className='main_about'>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero et blanditiis, vero molestias nostrum eius aliquam harum autem similique commodi totam vitae modi molestiae illo consequuntur sequi pariatur deleniti! Eveniet aperiam tempore voluptatem accusamus totam explicabo debitis consequuntur ipsa at. Minima quisquam consequatur, harum ut optio unde. Quod eos pariatur, nobis commodi est earum quam minima consectetur veritatis aliquid ducimus, similique magni molestiae perspiciatis repellendus error blanditiis ea soluta saepe hic. Repellat quos culpa dolor molestiae ducimus enim deserunt iure porro aliquid impedit? Quisquam laborum eos aliquam iste sit est beatae obcaecati, eligendi quis qui cumque eius, temporibus consequatur perferendis natus modi recusandae velit quaerat sunt molestiae tempore quibusdam quidem, consectetur similique. Nam cum repudiandae cupiditate, esse provident blanditiis exercitationem iste distinctio fuga odio, inventore numquam repellendus ad optio consequuntur amet velit maiores quisquam magnam! Necessitatibus impedit sapiente pariatur, placeat perspiciatis eum nam excepturi, quam, qui alias ab explicabo perferendis earum dolores blanditiis. Illum molestias pariatur similique veritatis optio impedit placeat provident aliquid corrupti recusandae, nobis deleniti, ab perspiciatis! Consectetur earum laboriosam veniam cum ullam. Facere in maiores tenetur, molestias sequi soluta dolorum animi neque ipsum, modi quam praesentium hic repellat. Incidunt quod reprehenderit soluta! Cumque quo possimus soluta natus! Molestias laboriosam repellendus repellat, veniam neque doloremque. Distinctio consequuntur recusandae non laudantium molestiae. Temporibus vero sit deserunt atque vel molestiae accusamus sequi eveniet incidunt mollitia ratione ex quaerat ea, repellendus, error maiores quisquam. Tempore, sed? Earum aliquid unde at sint repellat a minima delectus amet magni ea aperiam omnis provident odio vero voluptate expedita voluptatibus, iusto incidunt non repellendus qui molestias quam? Similique, non! Voluptatibus iure laborum recusandae accusantium id ex ducimus minus sint cumque facilis architecto autem cum, sit ab nesciunt dolores. Autem mollitia, illum incidunt voluptatem error doloribus labore nobis numquam accusantium esse nulla, libero inventore exercitationem cum?</p>
        </main>
    );
};

export default About;